// Package xir implements the XIR wire encoding of the contracts in
// contracts/src/XIREncoding.sol and of the Python reference runtime in
// src/xir_lab/native/xir_trace.py.
//
// Every derivation in this package is byte exact with both references; the
// parity test in vectors_test.go compares it against vectors generated by
// scripts/generate_go_parity_vectors.py.
package xir

import (
	"encoding/hex"
	"fmt"

	"golang.org/x/crypto/sha3"
)

// RegistryVersion is the root-registry version used by every campaign profile
// (src/xir_lab/native/multihop_deployer.py REGISTRY_VERSION).
const RegistryVersion uint32 = 1

// Typed identifier kinds (contracts/src/XIRTypes.sol).
const (
	KindEVM    uint8 = 1
	KindSolana uint8 = 2
)

var (
	tagRecord       = []byte("XIR_RECORD_V1")
	tagContext      = []byte("XIR_CONTEXT_V1")
	tagRID          = []byte("XIR_RID_V1")
	tagMID          = []byte("XIR_MID_V1")
	tagRoot         = []byte("XIR_ROOT_V1")
	tagTransition   = []byte("XIR_TRANSITION_V1")
	tagHop          = []byte("XIR_HOP_V1")
	tagPrefix       = []byte("XIR_PREFIX_V1")
	tagBundle       = []byte("XIR_BUNDLE_V1")
	tagBundleStep   = []byte("XIR_BUNDLE_STEP_V1")
	tagGatewayID    = []byte("XIR_NATIVE_MULTIHOP_GATEWAY_ID_V1")
	tagMultihopProf = []byte("XIR_NATIVE_MULTIHOP_PROFILE_V1")
)

// Keccak256 hashes the concatenation of the given byte slices.
func Keccak256(parts ...[]byte) [32]byte {
	hasher := sha3.NewLegacyKeccak256()
	for _, part := range parts {
		_, _ = hasher.Write(part)
	}
	var digest [32]byte
	hasher.Sum(digest[:0])
	return digest
}

// TypedID is a kind-prefixed chain-scoped identifier.
type TypedID struct {
	Kind  uint8
	Value []byte
}

// NewEVMID builds an EVM-kind typed identifier from a 20-byte address.
func NewEVMID(value []byte) (TypedID, error) {
	id := TypedID{Kind: KindEVM, Value: append([]byte(nil), value...)}
	if _, err := id.Bytes(); err != nil {
		return TypedID{}, err
	}
	return id, nil
}

// Bytes returns kind || length || value, matching XIREncoding.encodeTypedId.
func (t TypedID) Bytes() ([]byte, error) {
	expected := 0
	switch t.Kind {
	case KindEVM:
		expected = 20
	case KindSolana:
		expected = 32
	}
	if expected == 0 || len(t.Value) != expected {
		return nil, fmt.Errorf(
			"invalid XIR typed identifier: kind=%d length=%d", t.Kind, len(t.Value),
		)
	}
	out := make([]byte, 0, 2+len(t.Value))
	out = append(out, t.Kind, byte(len(t.Value)))
	return append(out, t.Value...), nil
}

// Hash returns keccak256 of the encoded identifier (XIREncoding.typedIdHash).
func (t TypedID) Hash() ([32]byte, error) {
	encoded, err := t.Bytes()
	if err != nil {
		return [32]byte{}, err
	}
	return Keccak256(encoded), nil
}

// EVMAddress returns the 20-byte address of an EVM-kind identifier.
func (t TypedID) EVMAddress() ([]byte, error) {
	if t.Kind != KindEVM || len(t.Value) != 20 {
		return nil, fmt.Errorf("identifier is not an EVM address: kind=%d", t.Kind)
	}
	return append([]byte(nil), t.Value...), nil
}

// Record is the application record carried across every hop.
type Record struct {
	SourceGateway  TypedID
	SourceApp      TypedID
	DestinationApp TypedID
	Nonce          uint64
	PayloadHash    [32]byte
}

// Context carries the required security level and policy commitment.
type Context struct {
	RequiredSecurity uint8
	PolicyHash       [32]byte
}

// Receipt is one verified hop of the trace.
type Receipt struct {
	SourceGateway      TypedID
	DestinationGateway TypedID
	ProfileHash        [32]byte
	EvidenceHash       [32]byte
	TransitionHash     [32]byte
	PriorPrefix        [32]byte
}

// Envelope is the delivered proof bundle.
type Envelope struct {
	Record          Record
	Context         Context
	RegistryVersion uint32
	Signature       []byte
	Receipts        []Receipt
}

// Hash returns the record digest (XIREncoding.recordHash).
func (r Record) Hash() ([32]byte, error) {
	parts := make([][]byte, 0, 6)
	parts = append(parts, tagRecord)
	for _, id := range []TypedID{r.SourceGateway, r.SourceApp, r.DestinationApp} {
		encoded, err := id.Bytes()
		if err != nil {
			return [32]byte{}, err
		}
		parts = append(parts, encoded)
	}
	parts = append(parts, uint64Bytes(r.Nonce), r.PayloadHash[:])
	return Keccak256(parts...), nil
}

// Hash returns the context digest (XIREncoding.contextHash).
func (c Context) Hash() [32]byte {
	return Keccak256(tagContext, []byte{c.RequiredSecurity}, c.PolicyHash[:])
}

// Hash returns the receipt digest (XIREncoding.receiptHash).
func (r Receipt) Hash() ([32]byte, error) {
	src, err := r.SourceGateway.Bytes()
	if err != nil {
		return [32]byte{}, err
	}
	dst, err := r.DestinationGateway.Bytes()
	if err != nil {
		return [32]byte{}, err
	}
	return Keccak256(
		tagHop,
		r.PriorPrefix[:],
		src,
		dst,
		r.ProfileHash[:],
		r.EvidenceHash[:],
		r.TransitionHash[:],
	), nil
}

// RootID returns the root identifier over record, context, and registry version
// (XIREncoding.rootId).
func RootID(record Record, context Context, registryVersion uint32) ([32]byte, error) {
	recordDigest, err := record.Hash()
	if err != nil {
		return [32]byte{}, err
	}
	contextDigest := context.Hash()
	id, err := record.SourceGateway.Bytes()
	if err != nil {
		return [32]byte{}, err
	}
	return Keccak256(tagRID, id, recordDigest[:], contextDigest[:], uint32Bytes(registryVersion)), nil
}

// MessageID returns the delivery identifier for a root and destination app
// (XIREncoding.messageId).
func MessageID(rid [32]byte, destinationApp TypedID) ([32]byte, error) {
	id, err := destinationApp.Bytes()
	if err != nil {
		return [32]byte{}, err
	}
	return Keccak256(tagMID, rid[:], id), nil
}

// RootPrefix returns the empty-trace prefix of a root (XIREncoding.rootPrefix).
func RootPrefix(rid [32]byte) [32]byte {
	return Keccak256(tagRoot, rid[:])
}

// TransitionHash returns the transition digest of one hop
// (XIREncoding.transitionHash).
func TransitionHash(record Record, context Context, source, destination TypedID) ([32]byte, error) {
	recordDigest, err := record.Hash()
	if err != nil {
		return [32]byte{}, err
	}
	src, err := source.Bytes()
	if err != nil {
		return [32]byte{}, err
	}
	dst, err := destination.Bytes()
	if err != nil {
		return [32]byte{}, err
	}
	contextDigest := context.Hash()
	return Keccak256(
		tagTransition, recordDigest[:], contextDigest[:], src, dst,
	), nil
}

// NextPrefix extends a prefix with one receipt (XIREncoding.nextPrefix).
func NextPrefix(priorPrefix [32]byte, receipt Receipt) ([32]byte, error) {
	receiptDigest, err := receipt.Hash()
	if err != nil {
		return [32]byte{}, err
	}
	return Keccak256(tagPrefix, priorPrefix[:], receiptDigest[:]), nil
}

// BundleStart starts the length-bound bundle commitment
// (XIREncoding.bundleStart, which uses abi.encode rather than packed bytes).
func BundleStart(receiptCount int) [32]byte {
	if receiptCount < 0 {
		panic("xir: negative receipt count")
	}
	encoded := make([]byte, 0, 128)
	encoded = append(encoded, word(64)...)
	encoded = append(encoded, word(uint64(receiptCount))...)
	encoded = append(encoded, word(uint64(len(tagBundle)))...)
	encoded = append(encoded, rightPad(tagBundle)...)
	return Keccak256(encoded)
}

// BundleStep extends a bundle commitment with one index-bound receipt tuple
// (XIREncoding.bundleStep).
func BundleStep(prefix [32]byte, index int, receipt Receipt) [32]byte {
	if index < 0 {
		panic("xir: negative bundle index")
	}
	encoded := make([]byte, 0, 256)
	encoded = append(encoded, word(192)...)
	encoded = append(encoded, prefix[:]...)
	encoded = append(encoded, word(uint64(index))...)
	encoded = append(encoded, receipt.ProfileHash[:]...)
	encoded = append(encoded, receipt.EvidenceHash[:]...)
	encoded = append(encoded, receipt.TransitionHash[:]...)
	encoded = append(encoded, word(uint64(len(tagBundleStep)))...)
	encoded = append(encoded, rightPad(tagBundleStep)...)
	return Keccak256(encoded)
}

// BundleCommitment folds every receipt into the bundle commitment that the
// final adapter must have recorded.
func BundleCommitment(receipts []Receipt) [32]byte {
	prefix := BundleStart(len(receipts))
	for index, receipt := range receipts {
		prefix = BundleStep(prefix, index, receipt)
	}
	return prefix
}

// ProfileHash returns the registered profile hash of one hop
// (src/xir_lab/native/multihop_deployer.py multihop_profile_hash).
func ProfileHash(route string, hopIndex int) ([32]byte, error) {
	if hopIndex < 1 || hopIndex > len(route) {
		return [32]byte{}, fmt.Errorf("multihop profile coordinates are invalid: route=%q hop=%d", route, hopIndex)
	}
	protocol := route[hopIndex-1 : hopIndex]
	return Keccak256([]byte(fmt.Sprintf(
		"%s:%s:%d:%s", tagMultihopProf, route, hopIndex, protocol,
	))), nil
}

// GatewayTypedID returns the XIR gateway identifier of one local chain
// (multihop_deployer.multihop_gateway_typed_id).
func GatewayTypedID(chainID uint64) (TypedID, error) {
	digest := Keccak256([]byte(fmt.Sprintf("%s:%d", tagGatewayID, chainID)))
	return NewEVMID(digest[12:])
}

// AdapterKey returns the deployment key of one route adapter
// (multihop_deployer.adapter_key).
func AdapterKey(route string, hopIndex int, direction string) (string, error) {
	if direction != "out" && direction != "in" {
		return "", fmt.Errorf("multihop adapter direction is invalid: %q", direction)
	}
	if hopIndex < 1 || hopIndex > len(route) {
		return "", fmt.Errorf("multihop adapter coordinates are invalid: route=%q hop=%d", route, hopIndex)
	}
	return fmt.Sprintf("route_%s_hop_%d_%s", lowerASCII(route), hopIndex, direction), nil
}

func lowerASCII(value string) string {
	out := []byte(value)
	for index, char := range out {
		if char >= 'A' && char <= 'Z' {
			out[index] = char + ('a' - 'A')
		}
	}
	return string(out)
}

// FormatDigest renders a digest in 0x-prefixed hexadecimal.
func FormatDigest(digest [32]byte) string {
	return "0x" + hex.EncodeToString(digest[:])
}

func uint64Bytes(value uint64) []byte {
	out := make([]byte, 8)
	for index := 7; index >= 0; index-- {
		out[index] = byte(value)
		value >>= 8
	}
	return out
}

func uint32Bytes(value uint32) []byte {
	out := make([]byte, 4)
	for index := 3; index >= 0; index-- {
		out[index] = byte(value)
		value >>= 8
	}
	return out
}

// word renders one 32-byte big-endian ABI word, as abi.encode does.
func word(value uint64) []byte {
	out := make([]byte, 32)
	for index := 31; index >= 24; index-- {
		out[index] = byte(value)
		value >>= 8
	}
	return out
}

func rightPad(value []byte) []byte {
	if len(value)%32 == 0 {
		return append([]byte(nil), value...)
	}
	out := make([]byte, len(value))
	copy(out, value)
	return append(out, make([]byte, 32-len(value)%32)...)
}
