[profile.default]
src = "src"
script = "script"
out = "out"
cache_path = "cache"
libs = ["lib"]
solc = "0.8.28"
auto_detect_solc = false
evm_version = "london"
optimizer = true
optimizer_runs = 200
via_ir = true
bytecode_hash = "none"
cbor_metadata = false
fs_permissions = [{ access = "read-write", path = "./deployments" }]

remappings = [
  "@openzeppelin/contracts/=lib/hyperlane/solidity/dependencies/@openzeppelin-contracts-4.9.3/contracts/",
  "@openzeppelin/contracts-upgradeable/=lib/hyperlane/solidity/dependencies/@openzeppelin-contracts-upgradeable-4.9.3/contracts/",
  "@arbitrum/nitro-contracts/src/=lib/hyperlane/solidity/dependencies/@arbitrum-nitro-contracts-1.2.1/src/",
  "@chainlink/contracts-ccip/src/v0.8/=lib/hyperlane/solidity/dependencies/@chainlink-contracts-ccip-1.5.0/contracts/src/v0.8/",
  "@eth-optimism/contracts/=lib/hyperlane/solidity/dependencies/@eth-optimism-contracts-0.6.0/packages/contracts/contracts/",
  "forge-std/=lib/hyperlane/solidity/dependencies/forge-std-1.9.2/src/",
]
