[profile.default]
src = "src"
script = "script"
test = "test"
out = "out"
cache_path = "cache"
libs = ["lib"]
solc = "0.8.28"
auto_detect_solc = false
evm_version = "london"
optimizer = true
optimizer_runs = 200
bytecode_hash = "none"
cbor_metadata = false

[fuzz]
runs = 256

[invariant]
runs = 128
depth = 32
fail_on_revert = false
